version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: ${REMOTE_MYSQL_DBNAME} 
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     container_name: wordpress-docker_mysql_${PROJECT_NICKNAME}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     volumes:
       - ./wp-content:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     container_name: wordpress-docker_wordpress_${PROJECT_NICKNAME}
volumes:
    db_data: {}
